auth:
  gateway:
    source: ${GATEWAY_IDENTITY_SOURCE}
    icon: ${GATEWAY_ICON}
    name: ${GATEWAY_NAME}
    user_name_changable: ${GATEWAY_USER_NAME_CHANGABLE}
    tips:
      nobody: ${GATEWAY_TIP_NOBODY}
      not_staff: ${GATEWAY_TIP_NOT_STAFF}