---
auth-default-group-401: gateway
auth:
  gateway:
    source: ${GATEWAY_IDENTITY_SOURCE}
    icon: ${GATEWAY_ICON}
    name: ${GATEWAY_NAME}
    login:
      url: ${GATEWAY_LOGIN_URL}
      tip: ${GATEWAY_LOGIN_TIP}
    user_name_changable: ${GATEWAY_USER_NAME_CHANGABLE}
    form_requires:
      school: ${GATEWAY_FORM_REQUIRES_SCHOOL}
      department: ${GATEWAY_FORM_REQUIRES_DEPARTMENT}
      campus: ${GATEWAY_FORM_REQUIRES_CAMPUS}
      building: ${GATEWAY_FORM_REQUIRES_BUILDING}
      room: ${GATEWAY_FORM_REQUIRES_ROOM} 
    tips:
      nobody: ${GATEWAY_TIP_NOBODY}
      not_staff: ${GATEWAY_TIP_NOT_STAFF}
gateway-teacher-types: ${GATEWAY_TEACHER_TYPES}
gateway-add-member-title: ${GATEWAY_ADD_MEMBER_TITLE}
...
